name: Test action

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        content_type:
          - text/plain
          - text/html
          - text/markdown
        include:
          - content_type: text/plain
            body: Test of action completed successfully!
          - content_type: text/html
            body: |
              <!DOCTYPE html>
              <html>
              <body>
              <h1>Heading</h1>
              <p>Paragraph</p>
              </body>
              </html>
          - content_type: text/markdown
            body: file://README.md
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Send mail
        uses: ./
        with:
          server_address: ${{secrets.ADDRESS}}
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: ${{github.repository}}
          body: ${{matrix.body}}
          to: ${{github.event.pusher.email}},${{secrets.USERNAME}}
          from: github-actions
          content_type: ${{matrix.content_type}}